# Configuração para Desenvolvimento Local
app:
  environment: "development"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "monetics_dev"

logger:
  level: "debug"
  format: "console"